run-single-node-cluster:
  cockroach start-single-node --insecure --listen-addr=localhost:26257 --http-addr=localhost:8080


run-cluster:
  # node 1
  cockroach start --insecure --listen-addr=localhost:26257 --join=localhost:26257,localhost:26258,localhost:26259 --http-addr=localhost:8080 --store=cockroach-data-1 --background
  # node 2
  cockroach start --insecure --listen-addr=localhost:26258 --join=localhost:26257,localhost:26258,localhost:26259 --http-addr=localhost:8081 --store=cockroach-data-2 --background
  # node 3
  cockroach start --insecure --listen-addr=localhost:26259 --join=localhost:26257,localhost:26258,localhost:26259 --http-addr=localhost:8082 --store=cockroach-data-3 --background

  # init cluster
  cockroach init --host localhost:26258 --insecure

  # add more to the cluster
  # cockroach start --insecure --listen-addr=localhost:26260 \
    --join=localhost:26257,localhost:26258,localhost:26259,localhost:26260,localhost:26261 --http-addr=localhost:8083 --store=cockroach-data-4 --background


init-database-for-load:
   cockroach workload init ycsb 'postgresql://root@localhost:26260?sslmode=disable'

load:
   cockroach workload run ycsb --duration=5m --concurrency=3 --max-rate=1000 --splits=50 'postgresql://root@localhost:26260?sslmode=disable'
